# Site wide configuration

title: Foat Akhmadeev
description: "Software development and research using Java and Scala."
logo: logo.jpg
teaser: teaser.jpg
locale: en_US
url: https://foat.me

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap

# Social icons
github_username: foat
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: akhmadeevfoat
angellist_username:

# Site owner
owner:
  name: Foat Akhmadeev
  email: foat.akhmadeev@gmail.com
  web: https://foat.me
  bio: "Software developer."
  avatar: bio-photo.jpg
  disqus-shortname: "foat-me"


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
